---
title: "📝 HW2"
editor: 
  markdown: 
    wrap: sentence
format: 
  html: 
    embed-resources: true
---

Due date: **Friday, September 18 at midnight**.

<!-- ⏳ We recommend reading through each problem ASAP so you can accurately estimate the time needed to complete the assignment.

-   This is not an assignment to start the night before the due date! -->

<!-- -   The assignment covers material all the way up to the Wednesday 9/11 lecture before the HW is due, so be sure to start working on problems as soon as you learn the requisite material. -->

<!-- Unless otherwise stated, assignments in STAT 131A are to be done individually.

-   As stated in the syllabus, the use of any LLM other than PingPong is considered cheating, unless otherwise indicated.

-   See the syllabus for the full course collaboration policy. -->

Some components of this assignment have not been seen by a previous cohort of STAT 131A students, so there may be some unforeseen hiccups.

-   If anything seems confusing or unclear, please create an Ed post. We are here to support you!

## 📮 Submission

Submit your assignment via [Pensive](https://www.pensive.com). The Pensive portal will be live at least a few days before the HW deadline.

- Write your answers on paper or a tablet. Submit a PDF of your answers.

-  **Make sure to tag your answers properly on Pensive, or else you will need to use slip days for every day day required to fix your work.** 


## 1. Histograms and boxplots (20%)

Answer each of the questions below. Then, write an explanation of at least one sentence, or make one drawing, to justify your choice.

a. For a fixed bin size and dataset, the shape of a frequency histogram is usually different than the shape of a density histogram. True or false?

b. For a fixed binwidth of 1, a relative frequency histogram for a set of values is identical to a density histogram for the same set of values. True or false?

c. What is the largest possible length of the lower whisker of a boxplot? What is the smallest possible length of the lower whisker? Would your answers differ for the upper whisker? 

## 2. Expected value and variance of a discrete random variable (20%)

```{r, echo=FALSE}
X <- c(1, 4, 10)
pmf <- c(.20, .3, .5)
```

A discrete random variable $X$ has the probability mass function

$$
\Pr(X=x) =
\begin{cases}
  `r pmf[1]` & \mathrm{if~} x = `r X[1]`, \\
  `r pmf[2]` & \mathrm{if~} x = `r X[2]`, \\
  `r pmf[3]` & \mathrm{if~} x = `r X[3]`. \\
\end{cases}
$$


a. What is $\mathbb{E}[X]$?

b. What is $\text{Var}(X)$?

## 3. Probability density function (PDF) practice (20%)

For the problem below, please show all steps.
You are welcome to use a scientific calculator for arithmetic (e.g., no need to do long division by hand).

Consider the function $f$ defined on the interval $[0,1]$ : $f(x) = cx^\frac{1}{3}$.

a.  Find the value of $c$ that makes $f$ a valid PDF for an r\.v\. $X$.

b.  What is $\Pr(0.1\leq X \leq 0.5)$?

c.  What is $\Pr(0 \leq X \leq x)$, for any $x$ in $(0,1)$?

d.  What is $\frac{d}{dx} \Pr(0\leq X \leq x)$? Why is this answer the same as part (a)?

e.  What is $\mathbb{E}(X)$?

f.  What is $\text{Var}(X)$?

## 4. Constructing an estimator (20%)

Dr. Siti Essus is interested in measuring the political attitudes of UC Berkeley students. 
To start, she designs a poll where she asks students to rate their political preferences from 1 to 7.
She uses the following scale:

* 1 - very liberal
* 2 - liberal
* 3 - somewhat liberal 
* 4 - moderate
* 5 - somewhat conservative
* 6 - conservative
* 7 - very conservative

Siti randomly samples 131 students from each class at UC Berkeley (131 freshmen, 131 sophomores, 131 juniors, and 131 seniors), for a total of 524 students. 

Siti hypothesizes that UC Berkeley seniors are more liberal than UC Berkeley freshmen. 
Let $X_{1,\text{f}}...X_{131,\text{f}}$ represent the 131 political preferences of the sampled freshmen, and $X_{1,\text{s}}...X_{131,\text{s}}$ represent the 131 political preferences of the sampled seniors.

Write the formula of an estimator that could be used to address Siti's hypothesis. There is more than one correct answer to this question. I encourage you to think about different possibilities.

## 5. Parallel universes (20%)

Answer each of the questions below. Then, write an explanation of at least one sentence, or make one drawing, to justify your choice.

a. The sampling distribution of an estimator is the distribution from which samples of data are generated. True or false?

b. The standard deviation of 2,000 values randomly drawn from a *probability distribution* is typically smaller than the standard deviation of 1,000 values drawn from the same distribution. True or false?

c. The standard deviation of 2,000 point estimates randomly drawn from a *sampling distribution* is typically smaller than the standard deviation of 1,000 point estimates drawn from the same distribution. True or false?
